<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2.2 (Python 3.12.1 on win32)" generated="2025-03-12T09:26:09.044058" rpa="false" schemaversion="5">
<suite id="s1" name="Test Suite" source="c:\Users\User\Desktop\ProjetosEstudos\Robot_Servrest_web\projeto-automacao\tests\test_suite.robot">
<test id="s1-t1" name="Rodar todos os testes" line="6">
<kw name="Run Tests">
<msg time="2025-03-12T09:26:09.075992" level="FAIL">No keyword with name 'Run Tests' found.</msg>
<arg>features/cadastro.robot</arg>
<status status="FAIL" start="2025-03-12T09:26:09.074992" elapsed="0.001999">No keyword with name 'Run Tests' found.</status>
</kw>
<kw name="Run Tests">
<arg>features/login.robot</arg>
<status status="NOT RUN" start="2025-03-12T09:26:09.076991" elapsed="0.000000"/>
</kw>
<status status="FAIL" start="2025-03-12T09:26:09.073991" elapsed="0.003999">No keyword with name 'Run Tests' found.</status>
</test>
<status status="FAIL" start="2025-03-12T09:26:09.047556" elapsed="0.031436"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="Test Suite" id="s1" pass="0" fail="1" skip="0">Test Suite</stat>
</suite>
</statistics>
<errors>
<msg time="2025-03-12T09:26:09.069595" level="ERROR">Error in file 'c:\Users\User\Desktop\ProjetosEstudos\Robot_Servrest_web\projeto-automacao\tests\test_suite.robot' on line 2: Error in file 'c:\Users\User\Desktop\ProjetosEstudos\Robot_Servrest_web\projeto-automacao\tests\features\cadastro.robot' on line 5: Resource file with 'Test Cases' section is invalid.</msg>
<msg time="2025-03-12T09:26:09.071992" level="ERROR">Error in file 'c:\Users\User\Desktop\ProjetosEstudos\Robot_Servrest_web\projeto-automacao\tests\test_suite.robot' on line 3: Error in file 'c:\Users\User\Desktop\ProjetosEstudos\Robot_Servrest_web\projeto-automacao\tests\features\login.robot' on line 5: Resource file with 'Test Cases' section is invalid.</msg>
</errors>
</robot>
